import type { GuideTopic } from '../guide'

// The customer question playbook of research/product-knowledge-for-counter-advice.md
// section 5: the question as asked at the counter, the sourced short answer, the products
// or bundle. Grouped by what the customer raises.
export const COUNTER_TOPICS: GuideTopic[] = [
  {
    id: 'counter-poultry',
    title: 'Counter questions: broilers, layers, ducks and tilapia',
    section: 'counter',
    summary: 'How many sacks for 100 chicks, when to switch feeds, how much a laying hen eats, when she starts, why layer mash is not for chicks.',
    paragraphs: [
      '"Ilang sako ng feeds para sa 100 sisiw hanggang 45 araw?" About 259 kg: 7 kg booster, 126 kg starter, 126 kg finisher on the DA program. Sell 3 sacks starter, 3 sacks finisher, booster in a small pack.',
      '"Kailan lumipat sa starter at finisher?" Booster to day 7 to 14, starter to day 28, finisher to day 42 to 45; Unifeeds switches at day 11 and day 29. Same brand, three stages, changed gradually.',
      '"Gaano karaming feeds ang kain ng manok na nangingitlog?" About 100 to 110 g per hen per day, 3.1 to 3.3 kg a month; 100 hens need about 6 sacks a month.',
      '"Kailan magsisimulang mangitlog?" At 20 to 22 weeks, peak at 30 to 36; switch to layer mash at about 19 weeks or 10 percent lay.',
      '"Pwede bang layer mash sa sisiw?" No: layer mash carries 3.5 percent calcium against 1 percent in chick feed; match the feed to the age.',
      '"Anong bakuna ng manok at kailan?" Newcastle at 8 to 10 days, fowl pox at 21 to 24, Newcastle again at 26 to 28; layers add Gumboro at 2 to 4 weeks and boosters during lay. Vaccine vials by dose count, an eye-dropper or drinking-water applicator, ice.',
      '"Anong pakain sa itik na nangingitlog?" Duck layer pellet at 105 to 120 g per duck per day from 16 weeks.',
      '"Gaano karami ang pakain sa tilapia?" 3 to 5 percent of body weight a day for fingerlings and growers under complete feeding, 2 to 3 percent with pond fertilization; feed = average weight x number of fish x rate.',
    ],
    sources: ['PK:5', 'PK:1.1', 'PK:1.2'],
    tags: ['feed', 'broiler', 'layer', 'duck', 'tilapia', 'vaccine'],
    related: ['broiler-feeding-program', 'layer-feeding-program', 'duck-quail-native-feeding', 'tilapia-feeding', 'vaccination-schedules'],
  },
  {
    id: 'counter-hogs',
    title: 'Counter questions: hogs and goats',
    section: 'counter',
    summary:
      'How much feed a pig eats to market, kilos per day by weight, the sow ration, iron and deworming days, the hog cholera and ASF vaccines, goat concentrate.',
    paragraphs: [
      '"Magkano ang feeds ng isang biik hanggang benta?" About 230 to 270 kg per pig from weaning to 80 to 90 kg over about five months: pre-starter 13 kg, starter 30 kg, grower 113 kg, finisher 73 to 110 kg. Sell by stage: roughly 1 bag pre-starter, 1 sack starter, 2 to 3 sacks grower, 2 sacks finisher per pig.',
      '"Ilang kilo kada araw ang pakain sa baboy?" By weight: 1.2 kg at 20 kg, 2.0 kg at 50 kg, 2.5 kg at 75 kg, 3.0 kg at 100 kg; B-MEG says 1.0 to 1.2 kg starter, 2.0 to 2.2 kg grower, 2.2 to 2.5 kg finisher.',
      '"Anong pakain sa inahing baboy?" Gestating 2.0 to 2.5 kg a day, lactating up to 4.5 kg or more, about 8 sacks per farrowing cycle.',
      '"Kailan ang iron injection at deworming ng biik?" Iron on day 3, repeat day 14; deworm 1 to 2 weeks after weaning. Iron dextran injectable, syringe, oral dewormer dosed per label.',
      '"Kailan ang bakuna sa hog cholera?" At weaning, one week before or after; breeders every 6 months. The CSF vaccine from the cold chain, syringe and needle.',
      '"May bakuna na ba sa ASF?" Under the government-controlled programme only; commercial sale awaits BAI certification, targeted for the third quarter of 2026 as of June 2026. Sell biosecurity: disinfectant, footbath, lime; refer to the municipal veterinarian.',
      '"Anong concentrate sa kambing?" 0.2 to 0.7 kg per head per day of 18 to 20 percent protein for growing does and bucks; 0.3 to 0.5 kg per litre of milk for lactating does; salt and mineral mix always.',
    ],
    sources: ['PK:5', 'PK:1.3', 'PK:1.6', 'PK:4.4'],
    tags: ['feed', 'hog', 'goat', 'vaccine', 'vetDrug'],
    related: ['hog-feeding-program', 'goat-cattle-feeding', 'vaccination-schedules', 'disease-status'],
  },
  {
    id: 'counter-gamefowl',
    title: 'Counter questions: gamefowl',
    section: 'counter',
    summary: 'What to feed a stag by age, how long conditioning runs, and the supplements that go with it.',
    paragraphs: [
      '"Ano ang pakain sa panabong na stag?" Chick booster to 30 days ad libitum; developer to 4 months (50 to 60 g a day at 3 to 4 months); 60 to 100 g a day at 4 to 6 months; maintenance 35 to 50 g twice a day; conditioning 35 to 45 g per feeding.',
      '"Ilang araw ang conditioning?" 14, 21 or 30-day plans on a fixed schedule; 21 days is common; monitor weight and adjust. Conditioning feed, grains, B-complex and the supplement range.',
    ],
    sources: ['PK:5', 'PK:1.4'],
    tags: ['feed', 'gamefowl', 'vitamin'],
    related: ['gamefowl-feeding-program', 'derby-calendar', 'vitamins-and-supplements'],
  },
  {
    id: 'counter-rice',
    title: 'Counter questions: rice and corn',
    section: 'counter',
    summary:
      'Bags of fertilizer per hectare, when to apply urea, what MOET is, zinc deficiency, seed rates, the typhoon-season variety, corn seed and fertilizer, fall armyworm.',
    paragraphs: [
      '"Ilang sako ng abono sa isang ektarya ng palay?" Wet season, 5 t target: 4 bags of 14-14-14 at 10 to 14 days after transplanting, then 1 bag of urea per leaf colour chart trigger. Dry season, 7 t target: 6 bags of 14-14-14, then 1.5 bags of urea per trigger. Budget option: 1 bag complete plus 1 bag urea plus half a bag of 0-0-60 with 10 bags of manure for 3 to 4 t.',
      '"Kailan mag-urea?" Read the leaf colour chart weekly from 14 days after transplanting; apply when 6 of 10 leaves read below 4. Without a chart, at 0 to 14 days and 5 to 7 days before panicle initiation.',
      '"Ano ang MOET?" A PhilRice pot test that shows which nutrient the soil lacks and how much fertilizer a target yield needs; kits and the MOET app come from PhilRice.',
      '"Kulang sa zinc ang palay ko" (stunted, brown spots 2 to 4 weeks after transplanting): 25 kg of zinc sulfate per hectare broadcast at 10 to 14 days, or a 2 percent zinc oxide seedling dip, or 1 kg of zinc sulfate per 40 kg of seed for direct seeding.',
      '"Ilang kilo ng binhi ng palay?" Certified inbred 20 to 40 kg per hectare transplanted (40 is the PhilRice campaign rate), 40 to 60 kg row-seeded, 60 to 80 kg broadcast; hybrid about 20 kg.',
      '"Anong barayti ang bagay sa tag-ulan?" A variety recommended for the region and ecosystem with a maturity that escapes typhoons (PSB Rc10 at 106 days is the example), lodging and shattering tolerance, an NSQCS tag and at least 85 percent germination; text the PhilRice Text Center at 0917 111 7423.',
      '"Ilang kilo ng binhi ng mais?" 18 kg per hectare hybrid or GM, 20 kg open-pollinated.',
      '"Abono sa mais?" The DA program gives 2 bags per hectare (urea and complete); a 1987 trial shows 2 bags of urea alone lifts yield 41 percent; the full rate per the seed company\'s or the DA regional guide.',
      '"May uod sa mais" (fall armyworm): pheromone traps, Trichogramma and Metarhizium biocontrols, and a registered insecticide at the label rate; DA regional offices distribute lures and biocontrol agents.',
    ],
    sources: ['PK:5', 'PK:2.1', 'PK:2.2', 'PK:3.1', 'PK:3.2'],
    tags: ['fertilizer', 'seed', 'rice', 'corn'],
    related: ['rice-inputs', 'corn-inputs', 'seeds', 'fertilizer'],
  },
  {
    id: 'counter-vegetables',
    title: 'Counter questions: vegetables',
    section: 'counter',
    summary: 'Grams of tomato or eggplant seed, ampalaya seed, vegetable fertilizer, aphids and thrips, fruit fly, downy mildew.',
    paragraphs: [
      '"Ilang gramo ng binhi ng kamatis o talong?" 100 to 200 g per hectare, about 250 seeds per gram, transplant at 25 to 30 days.',
      '"Binhi ng ampalaya?" 3 kg per hectare, one pre-germinated seed per hill, furrows 2 m apart in the dry season or 3 m in the wet.',
      '"Abono sa gulay?" Tomato: 20 bags of manure per hectare, 14-14-14 a tablespoon per plant basal, urea a tablespoon per plant at 10 to 15 and 30 days with potash. Ampalaya: 14-14-14 at 20 g per hill, urea 10 g per hill every two weeks.',
      '"May aphids, thrips o whitefly sa kamatis": spray a registered insecticide for that pest at the label rate as the need arises; rotate varieties and sanitation first.',
      '"May fruit fly sa ampalaya": bag the fruits with newspaper or plastic; spray an appropriate insecticide at the manufacturer\'s rate.',
      '"Downy mildew sa ampalaya": remove infected leaves, spray an appropriate fungicide.',
    ],
    sources: ['PK:5', 'PK:2.3', 'PK:3.3'],
    tags: ['seed', 'fertilizer', 'pesticide', 'vegetables'],
    related: ['vegetable-inputs', 'pesticide-classes'],
  },
  {
    id: 'counter-pesticides',
    title: 'Counter questions: pests, weeds, snails, rats and pesticide safety',
    section: 'counter',
    summary: 'Stem borer, planthopper, blast, herbicide timing, kuhol, daga, how much per 16 litres, what the label colour means, paraquat, spills, PPE.',
    paragraphs: [
      '"Stem borer sa palay": spray a systemic insecticide at the base only when deadhearts exceed 30 percent at early tillering or whiteheads 20 percent at flowering; no spraying against leaf feeders in the first 30 to 40 days.',
      '"BPH o hopper": threshold 25 to 100 insects per hill by stage; conserve spiders and natural enemies; resistant varieties.',
      '"Blast o sheath blight": thresholds 30 percent leaf blast at tillering, 10 percent neck blast at flowering, 40 percent sheath blight; avoid excess nitrogen; fungicide per label.',
      '"Herbicide sa palay?" Control weeds within 0 to 45 days; land preparation, water and manual weeding first; herbicide as the last option, in the first 40 days after transplanting.',
      '"Kuhol": keep the field saturated to 25 days after sowing or 15 after transplanting, canals and attractants, screens at the inlets; molluscicide when needed.',
      '"Daga": community-wide control, fill the burrows, sanitation, rodenticide and traps up to two weeks before harvest.',
      '"Gaano karami ang ihahalo sa 16 litro?" Read the label\'s directions for use with the customer: the rate per tank, sprays per season and days to harvest are printed there.',
      '"Ano ang ibig sabihin ng kulay sa label?" Green least toxic (caution), blue caution or warning (moderate), yellow harmful or danger (high), red dangerous (banned).',
      '"Meron ba kayong paraquat o endosulfan?" No: endosulfan has been banned since 2015 and paraquat is restricted to institutional use only.',
      '"Natapunan ng pestisidyo, ano gagawin?" Skin: wash with soap and water, change clothes. Eyes: rinse for 15 minutes. Swallowed: do not force vomiting unless the label says so. Go to the doctor with the label.',
      '"Anong PPE?" Gloves, goggles and the protective gear stated on the label: nitrile gloves, goggles, mask, long sleeves, boots.',
    ],
    sources: ['PK:5', 'PK:2.4', 'PK:2.5', 'PK:2.6'],
    tags: ['pesticide'],
    related: ['pesticide-classes', 'pesticide-safety', 'banned-and-restricted-pesticides'],
  },
  {
    id: 'counter-animal-health',
    title: 'Counter questions: antibiotics, withdrawal, rabies, bird flu, carrying vaccines',
    section: 'counter',
    summary:
      'Whether a customer may buy an antibiotic for a hog, how long before slaughter after a drug, the dog vaccine, whether chicks are safe to buy, how to carry a vaccine home.',
    paragraphs: [
      '"Pwede bang bumili ng antibiotic para sa baboy?" Prescription antibiotics need a veterinarian\'s prescription; OTC products are sold in their original packs; the withdrawal period is on the label; banned drugs (chloramphenicol, nitrofurans, beta-agonists) are never sold.',
      '"Gaano katagal bago katayin pagkatapos ng gamot?" The withdrawal period printed on the label for that product; strict implementation is mandated.',
      '"Bakuna sa aso?" Rabies vaccination by a veterinarian, a registration card, yearly programmes at the municipal office; owners who do not register and vaccinate are fined PHP 2,000.',
      '"Bird flu, safe ba bumili ng sisiw?" H5N1 has been present since 2022, with a July 2026 backyard outbreak in Oriental Mindoro; buy chicks from accredited hatcheries, keep footbaths and disinfectant, report deaths to the BAI.',
      '"Paano dalhin ang bakuna pauwi?" In an ice box, away from disinfectants and chlorinated water, used the same day.',
    ],
    sources: ['PK:5', 'PK:4.2', 'PK:4.3', 'PK:4.4', 'PK:4.5'],
    tags: ['vetDrug', 'vaccine', 'disinfectant'],
    related: ['dosage-and-withdrawal', 'vaccination-schedules', 'disease-status', 'cold-chain'],
  },
]
